# Generated by Django 2.2.4 on 2020-08-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_share_shareditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='items',
            field=models.ManyToManyField(to='core.SharedItem'),
        ),
    ]
