# Generated by Django 2.2.4 on 2020-09-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200902_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dispatched',
            field=models.BooleanField(default=False),
        ),
    ]
