# Generated by Django 2.2.4 on 2020-09-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_order_dispatched'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.BooleanField(default=True),
        ),
    ]
