# Generated by Django 2.2.4 on 2020-09-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_item_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
