# Generated by Django 2.2.4 on 2020-10-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20201021_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dispatched_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
