# Generated by Django 2.2.4 on 2020-10-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20201021_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_rate',
            field=models.BooleanField(default=True),
        ),
    ]
