# Generated by Django 2.2.4 on 2020-11-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20201106_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='special_requirement',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
