# Generated by Django 2.2.4 on 2020-11-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_orderitem_special_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='special_requirement',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rate_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Regular Rate'), (1, 'Box Rate')]),
        ),
    ]
