# Generated by Django 2.2.4 on 2020-11-06 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20201106_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Transport'),
            preserve_default=False,
        ),
    ]
