# Generated by Django 2.2.4 on 2020-11-06 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20201106_0752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='total_priece',
            new_name='total_price',
        ),
    ]
