# Generated by Django 2.2.4 on 2020-11-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20201106_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_price',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_grand',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_tax',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
