# Generated by Django 2.2.4 on 2020-11-06 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20201106_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Transport'),
        ),
    ]
