# Generated by Django 2.2.4 on 2020-11-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20201106_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lr',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
