# Generated by Django 2.2.4 on 2020-11-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_order_lr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lr',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
