# Generated by Django 2.2.4 on 2020-11-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20201117_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelist',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
