# Generated by Django 2.2.4 on 2020-12-16 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='one_click_purchasing',
            new_name='full_access',
        ),
    ]
