# Generated by Django 2.2.4 on 2020-12-16 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20201216_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='full_access',
        ),
    ]
