# Generated by Django 2.2.4 on 2020-12-16 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_userprofile_full_access'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='full_access',
            new_name='one_click_purchasing',
        ),
    ]
