# Generated by Django 2.2.4 on 2020-12-18 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_userprofile_full_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='stripe_customer_id',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
