# Generated by Django 2.2.4 on 2020-12-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20201218_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='valid_till',
            field=models.DateField(blank=True, null=True),
        ),
    ]
