# Generated by Django 2.2.4 on 2021-01-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_gst_numbers_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gst',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
