# Generated by Django 2.2.4 on 2021-02-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20210106_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='set',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
