# Generated by Django 2.2.4 on 2021-02-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20210211_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
