# Generated by Django 2.2.4 on 2020-10-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loggedinuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedinuser',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
